In [555]:
import pandas as pd

In [556]:
df=pd.read_csv('unclean_smartwatch_health_data.csv')
df.head()

,User ID,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,4174.0,58.939776,98.809650,5450.390578,7.167235622316564,Highly Active,1
1,NaN,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
2,1860.0,247.803052,97.052954,2826.521994,ERROR,Highly Active,5
3,2294.0,40.000000,96.894213,13797.338044,7.367789630207228,Actve,3
4,2130.0,61.950165,98.583797,15679.067648,NaN,Highly_Active,6

In [557]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User ID                 9799 non-null   float64
 1   Heart Rate (BPM)        9600 non-null   float64
 2   Blood Oxygen Level (%)  9700 non-null   float64
 3   Step Count              9900 non-null   float64
 4   Sleep Duration (hours)  9850 non-null   str
 5   Activity Level          9800 non-null   str
 6   Stress Level            9800 non-null   str
dtypes: float64(4), str(3)
memory usage: 547.0 KB

In [558]:
df['User ID'].isnull().sum()

np.int64(201)

In [559]:
df.drop(columns=['User ID'],inplace=True)

In [560]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        9600 non-null   float64
 1   Blood Oxygen Level (%)  9700 non-null   float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 468.9 KB

In [561]:
df['Heart Rate (BPM)'].isnull().sum()

np.int64(400)

In [562]:
df[df['Heart Rate (BPM)'].isnull()==True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
1,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
17,NaN,96.052853,3488.919508,6.718661172525927,Seddentary,4
75,NaN,100.000000,3124.118038,4.229887888280923,Actve,1
105,NaN,98.276558,3039.112276,5.209658021888749,NaN,6
158,NaN,99.478461,11559.663606,6.470651489160172,Highly_Active,7
...,...,...,...,...,...,...
9875,NaN,99.842527,4454.770218,5.520745925308887,Sedentary,3
9956,NaN,100.000000,3584.236177,6.659533807452561,Highly_Active,5
9971,NaN,99.319841,26.215769,6.367659085134144,Active,10
9990,NaN,100.000000,3817.269018,8.595259517189332,Seddentary,2
9998,NaN,98.401058,3364.788855,5.691233932149209,Active,8

In [563]:
df['Heart Rate (BPM)'].describe()

count    9600.000000
mean       76.035462
std        19.412483
min        40.000000
25%        64.890152
50%        75.220601
75%        85.198249
max       296.593970
Name: Heart Rate (BPM), dtype: float64

In [564]:
df['Heart Rate (BPM)']=df['Heart Rate (BPM)'].fillna(df['Heart Rate (BPM)'].median())

In [565]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  9700 non-null   float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 468.9 KB

In [566]:
df['Blood Oxygen Level (%)'].isnull().sum()

np.int64(300)

In [567]:
df[df['Blood Oxygen Level (%)'].isnull()==True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
10,101.914938,NaN,2987.568640,7.541956463173237,Sedentary,9
21,68.310104,NaN,1058.374274,6.456918401449286,Actve,3
133,77.907578,NaN,15672.467752,9.079469571860296,Sedentary,10
134,78.227923,NaN,789.365922,3.5252990125882064,Seddentary,3
187,89.486636,NaN,2689.849911,5.737108446097524,Seddentary,6
...,...,...,...,...,...,...
9834,64.803112,NaN,1647.308449,8.04238137746177,Highly Active,7
9861,57.617790,NaN,14269.737149,6.390686112594759,Highly_Active,9
9885,75.281591,NaN,3852.160740,8.970316986352344,Actve,NaN
9905,87.693723,NaN,2364.028205,3.5490963940132865,Seddentary,3
9979,58.797407,NaN,359.210435,8.035879532058063,Active,5

In [568]:
df['Blood Oxygen Level (%)'].describe()

count    9700.000000
mean       97.841581
std         1.732863
min        90.791208
25%        96.662683
50%        98.010642
75%        99.376179
max       100.000000
Name: Blood Oxygen Level (%), dtype: float64

In [569]:
df['Blood Oxygen Level (%)']=df['Blood Oxygen Level (%)'].fillna(df['Blood Oxygen Level (%)'].mean())
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 468.9 KB

In [570]:
df['Step Count'].isnull().sum()

np.int64(100)

In [571]:
df[df['Step Count'].isnull()==True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
136,70.593014,97.473981,NaN,3.439287691081752,Highly_Active,6
204,75.220601,98.710637,NaN,5.756958709255954,Highly_Active,8
603,69.084103,99.627473,NaN,6.358184719715759,Highly_Active,7
716,83.258294,98.704757,NaN,5.486240700986009,Seddentary,3
739,97.506420,97.651407,NaN,7.465981460156365,Active,6
...,...,...,...,...,...,...
9097,62.072133,96.810967,NaN,5.828570383973958,Seddentary,6
9121,54.793814,99.670176,NaN,6.686430627866978,Seddentary,2
9191,101.777396,100.000000,NaN,8.07989468005159,Active,10
9527,75.220601,94.694312,NaN,4.186856483292383,Seddentary,4
9565,90.411615,95.009355,NaN,8.582820460042822,Sedentary,4

In [572]:
df['Step Count'] = df['Step Count'].ffill()

In [573]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 468.9 KB

In [574]:
df['Sleep Duration (hours)']=pd.to_numeric(df['Sleep Duration (hours)'],errors='coerce').astype('float32')
df['Sleep Duration (hours)'].describe()

count    9603.000000
mean        6.505463
std         1.510029
min        -0.194453
25%         5.493820
50%         6.503308
75%         7.529357
max        12.140233
Name: Sleep Duration (hours), dtype: float64

In [575]:
df[df['Sleep Duration (hours)'].isnull()==True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
2,247.803052,97.052954,2826.521994,NaN,Highly Active,5
4,61.950165,98.583797,15679.067648,NaN,Highly_Active,6
33,80.243365,100.000000,6848.558834,NaN,Sedentary,6
62,115.078288,99.928041,1918.372142,NaN,Highly_Active,4
71,64.799778,94.743857,4613.859266,NaN,Highly_Active,10
...,...,...,...,...,...,...
9901,63.369107,96.229029,6656.786482,NaN,Active,4
9912,75.933666,97.386073,1813.072248,NaN,Sedentary,10
9927,87.579045,98.768633,3727.161872,NaN,Active,1
9943,91.834863,96.145378,38831.465057,NaN,Active,4
9951,70.335328,98.560133,1997.442874,NaN,Highly_Active,9

In [576]:
df['Sleep Duration (hours)']=df['Sleep Duration (hours)'].fillna(df['Sleep Duration (hours)'].median())
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  10000 non-null  float32
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float32(1), float64(3), str(2)
memory usage: 429.8 KB

In [577]:
df['Activity Level'].mode()

0    Seddentary
Name: Activity Level, dtype: str

In [578]:
df['Activity Level']=df['Activity Level'].fillna('Seddentary')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  10000 non-null  float32
 4   Activity Level          10000 non-null  str
 5   Stress Level            9800 non-null   str
dtypes: float32(1), float64(3), str(2)
memory usage: 429.8 KB

In [579]:
df.tail()

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
9995,78.819386,98.931927,2948.491953,7.402749,Active,7
9996,48.632659,95.773035,4725.623070,6.382166,Sedentary,2
9997,73.834442,97.945874,2571.492060,6.916549,Sedentary,4
9998,75.220601,98.401058,3364.788855,5.691234,Active,8
9999,70.063864,98.475606,544.696104,5.691001,Actve,5

In [580]:
df['Stress Level'].value_counts()

Stress Level
2            1007
7            1006
6            1001
3             995
1             984
9             976
4             966
10            954
5             945
8             917
Very High      49
Name: count, dtype: int64

In [581]:
df['Stress Level']=df['Stress Level'].fillna(5)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  10000 non-null  float32
 4   Activity Level          10000 non-null  str
 5   Stress Level            10000 non-null  object
dtypes: float32(1), float64(3), object(1), str(1)
memory usage: 429.8+ KB

In [582]:
df=pd.read_csv('unclean_smartwatch_health_data.csv')

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User ID                 9799 non-null   float64
 1   Heart Rate (BPM)        9600 non-null   float64
 2   Blood Oxygen Level (%)  9700 non-null   float64
 3   Step Count              9900 non-null   float64
 4   Sleep Duration (hours)  9850 non-null   str
 5   Activity Level          9800 non-null   str
 6   Stress Level            9800 non-null   str
dtypes: float64(4), str(3)
memory usage: 547.0 KB

In [583]:
df=df.drop(columns=['User ID'])

In [584]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy='median')
imputer1=SimpleImputer(strategy='mean')
imputer2=SimpleImputer(strategy='most_frequent')
imputer3=SimpleImputer(strategy='constant',fill_value=5)

In [586]:
df['Heart Rate (BPM)']=imputer.fit_transform(df[['Heart Rate (BPM)']]).ravel()
df['Blood Oxygen Level (%)']=imputer1.fit_transform(df[['Blood Oxygen Level (%)']]).ravel()
df['Activity Level']=imputer2.fit_transform(df[['Activity Level']]).ravel()
df['Stress Level']=imputer3.fit_transform(df[['Stress Level']]).ravel()
df.info( )

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          10000 non-null  str
 5   Stress Level            10000 non-null  object
dtypes: float64(3), object(1), str(2)
memory usage: 468.9+ KB